### ISSUE TITLE
feat: keep timeline history for archive rooms in memory - [merged]

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#1380]
In GitLab by @h.carnot on Apr 8, 2022, 11:54

_Merges henri/fix-timeline-history -> main_

### Description
Fixes #275 #311 

For archived rooms, we don't want to store the events in the database.
For this, we store the sync response containing all the timeline for the archived rooms in memory and ask explicitly the sync handler to not update the database.

## TODO

- [x] : Initial implementation
- [x] : Rewrite `requestHistory` to not save requested events in the database for archived rooms.
- [x] : Verify that we can decrypt the events without needing to save the event update.
- [x] : What if we are suddenly re-invited in a archived room. See if the timeline is properly discarded.
- [x] : Provide a way to discard _archivedRooms. What if this take too much ram ?
- [x] : Tests

### Checklist
* [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
* [ ] I updated/added relevant documentation (doc comments with ///).
* [ ] I did not add or update methods, functions or widgets without tests.
