### ISSUE TITLE
feat: non cached fragmented timeline - [merged]

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#1383]
In GitLab by @h.carnot on Apr 13, 2022, 10:58

_Merges henri/fragmented-timeline -> main_

### Description

fix #278 

**Important:** This PR allows getting the timeline at a specific point in the history. However, the result won't be cached, so don't call this function with caution.

Also, when scrolling through history, new received event's won't be added to the timeline, but `onNewEvent` will be called.
So **don't let the user send messages when scrolling through history** as it may confuse him because fake events won't be added.

### The proposal

This proposal is to allow loading the timeline at a specific point.
However, when doing so, we don't store the events.

For this, we added

* `room.getTimelineOnEventContext` which will try to load the timeline context around a specific event, first in the database, then from the server.
* To call the getEventContext from the server, we added `room.getEventContext`. Calling this function will only return the new events and not add them to the local database. Thus, it won't trigger `onSyncUpdate`.
* `onlySending` parameter to `database.getEventList` to get only the fake events in the timeline. This is used when scrolling thought timeline next events after `getEventContext` to add them when we reached the last sent items.
* `timeline.getRoomEvents` get the events after or before the timeline. (See the `direction` parameter, refer the spec)
* some tests
* `timeline.onNewEvent` called when a new event is received
* `timeline.allowNewEvent` indicate if new event will be added in the timeline or ignored.
* `timeline.isFragmentedTimeline` indicate if the timeline was loaded from the database or not. If false, events got when requesting history or future won't be added. So don't user `room.requestHistory` but rather, `timeline.requestHistory` which use the patched logic.

### TODO
- [x] : Tests

### Checklist
* [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
* [ ] I updated/added relevant documentation (doc comments with ///).
* [ ] I did not add or update methods, functions or widgets without tests.
