### ISSUE TITLE
Update voip signaling to MSC2746/voip version 1

### ISSUE THREAD

**Issue by famedly-bot** [famedly/matrix-dart-sdk#181]
In GitLab by @nico-famedly on Jul 30, 2021, 11:05

#### Description
https://github.com/matrix-org/matrix-doc/pull/2746 adds support for renegotiation, better multi device reliability and DTMF. We should update our signaling to be compatible with that, even if we don't use some of those features like DTMF.

There are 3 PRs related to this issue:

* [x] [Done] Add necessary Call event keys. [matrix_api_lite #33](https://gitlab.com/famedly/company/frontend/libraries/matrix_api_lite/-/merge_requests/33) 
* [x] [WIP] Add new Call API and Event stream. [famedlysdk #763](https://gitlab.com/famedly/company/frontend/famedlysdk/-/merge_requests/763)
* [x] [WIP] Upgrade the [Famedly App #2021](https://gitlab.com/famedly/app/-/merge_requests/2021)

We need to merged PRs one by one and created a pub package version upgrade, bump the version in pubspec.yaml.

New feature status table

* [x] [Done] Compatible with Element
* [x] [Done] Select Answer, 
* [x] [Done] Multi-stream, Mic/Camera + Screen Sharing [SDK]
* [x] [WIP]  Change Calling UI layout to display Local (UserMedia + Screen Sharing) Remote (UserMedia + Screen Sharing), Add Screen Sharing Button [UI]
* [x] [Done] Mute/Unmute status remote synchronization [SDK]
* [x] [WIP]  Refactor the Stream Widget, display the mic muted status icon, and display the first letter avatar of the name when video muted [UI]
* [x] [Done] Hold/Unhold [SDK]
* [x] [WIP] Add Hold/Unhold Button and status switch [UI]
